# Generated by Django 4.2.5 on 2023-10-04 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('ShippingAddress_ID', models.IntegerField(primary_key='true', serialize=False)),
                ('ShippingAddress', models.CharField(max_length=70, null='false')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('Shipping_ID', models.IntegerField(primary_key='true', serialize=False)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ShippingAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipping.shippingaddress')),
            ],
        ),
    ]
