# Generated by Django 4.2.5 on 2023-10-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('Shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='Order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Order.order'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='Shipping_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='ShippingAddress_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
