# Generated by Django 4.2.5 on 2023-10-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_alter_book_book_id'),
        ('Cart', '0003_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(to='Book.book'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
