# Generated by Django 4.2.5 on 2023-10-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shipping', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='shippingAddress',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Shipping.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
