# Generated by Django 4.2.5 on 2023-10-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_ID', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publication_Date', models.DateField()),
                ('publisher', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('page_Count', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('cover_Type', models.CharField(max_length=50)),
            ],
        ),
    ]
